#!/usr/bin/env python3
"""
OpenSage Topology Demo

Demonstrates both topology modes described in the OpenSage paper:

1. VERTICAL TOPOLOGY: Sequential task decomposition
   "vertical agent topology, which decomposes complex tasks into sequential
   sub-tasks to be completed by specialized sub-agents"

2. HORIZONTAL TOPOLOGY: Parallel agent ensemble
   "horizontal agent topology, where multiple sub-agents simultaneously
   execute the same task using distinct plans, with their results
   integrated through an agent ensemble mechanism"

The paper notes: "No existing ADKs support AI-created agent topologies,
meaning domain experts have to manually design the agent structure."

OpenSage changes this: the LLM itself decides and creates the topology.

Usage:
    python demo/topology_demo.py

Set ANTHROPIC_API_KEY to run with real Claude.
"""

import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def demo_topology_concepts():
    """Show topology concepts without API calls."""
    print("=" * 70)
    print("  OpenSage: Self-Generated Agent Topology Demo")
    print("=" * 70)

    print("""
┌─────────────────────────────────────────────────────────────────┐
│  OpenSage Topology: From Human-Centered to AI-Centered           │
│                                                                   │
│  Traditional ADKs (OpenHands, LangChain, Google ADK):           │
│  - Human designs agent topology manually                         │
│  - Static sub-agents with fixed roles                           │
│  - Sub-agent states discarded after execution                   │
│                                                                   │
│  OpenSage:                                                       │
│  - LLM creates topology dynamically at runtime                  │
│  - Agents spawn sub-agents as needed (vertical)                 │
│  - Multiple agents run in parallel (horizontal)                 │
│  - Sub-agent states preserved and shared                        │
└─────────────────────────────────────────────────────────────────┘
""")

    # ------------------------------------------------------------------ #
    # VERTICAL TOPOLOGY visualization                                     #
    # ------------------------------------------------------------------ #
    print("=" * 70)
    print("1. VERTICAL TOPOLOGY (Sequential Decomposition)")
    print("=" * 70)
    print("""
Task: "Fix security vulnerability CVE-2024-XXXX in authentication module"

SageAgent (parent) uses LLM to decompose:
│
├── Sub-agent: vulnerability_analyzer
│   System: "You are a security analyst specializing in CVE analysis"
│   Tools: [read_file, search_code, analyze_code]
│   Task: Locate and understand the vulnerability
│   ↓ passes findings →
│
├── Sub-agent: patch_developer
│   System: "You are a security engineer who writes secure patches"
│   Tools: [read_file, write_file, run_python, create_tool]
│   Task: Develop a fix based on vulnerability analysis
│   Context: ← receives findings from vulnerability_analyzer
│   ↓ passes patch →
│
├── Sub-agent: test_engineer
│   System: "You are a QA engineer specializing in security testing"
│   Tools: [run_tests, run_python, search_code]
│   Task: Write and run tests to verify the patch
│   Context: ← receives patch from patch_developer
│   ↓ passes results →
│
└── Sub-agent: report_writer
    System: "You write clear security incident reports"
    Tools: [read_file, write_file]
    Task: Document the fix for the security report
    Context: ← receives all findings + test results

Final: Parent synthesizes all sub-agent outputs into a complete solution

Key insight: Each sub-agent is created with tailored prompts, tools, and
context - NOT pre-defined by humans, but dynamically generated by the LLM.
""")

    # ------------------------------------------------------------------ #
    # HORIZONTAL TOPOLOGY visualization                                   #
    # ------------------------------------------------------------------ #
    print("=" * 70)
    print("2. HORIZONTAL TOPOLOGY (Parallel Ensemble)")
    print("=" * 70)
    print("""
Task: "Implement a high-performance sorting algorithm for large datasets"

SageAgent launches 3 parallel agents with different strategies:

           ┌─────────────────────────────────────────────┐
           │            Task (same for all)               │
           └──────────┬────────────────┬─────────────────┘
                      │                │
         ┌────────────▼─┐    ┌────────▼──────┐    ┌────────▼──────┐
         │  Agent:       │    │  Agent:        │    │  Agent:        │
         │  systematic   │    │  heuristic     │    │  exhaustive    │
         │               │    │                │    │                │
         │ Strategy:     │    │ Strategy:      │    │ Strategy:      │
         │ - Analyze     │    │ - Use domain   │    │ - Try multiple │
         │   problem     │    │   knowledge    │    │   approaches   │
         │ - Form hyp.   │    │ - Quick path   │    │ - Verify all   │
         │ - Test steps  │    │ - Then valid.  │    │   edge cases   │
         └───────┬───────┘    └──────┬─────────┘    └───────┬───────┘
                 │                   │                       │
                 └───────────────────┴───────────────────────┘
                                     │
                         ┌───────────▼───────────┐
                         │   Integrator (LLM)     │
                         │ - Compare solutions    │
                         │ - Select best          │
                         │ - Synthesize insights  │
                         └───────────┬────────────┘
                                     │
                            Final Best Solution

Key insight: Different strategies surface different aspects of the solution.
The ensemble is more robust than any single agent.
""")

    # ------------------------------------------------------------------ #
    # ABLATION study from the paper                                       #
    # ------------------------------------------------------------------ #
    print("=" * 70)
    print("3. Ablation Study Results (from paper)")
    print("=" * 70)
    print("""
The paper tests 3 ablation configurations:

  Config          │ CyberGym  │ Terminal-B │ SWE-Pro
  ────────────────┼───────────┼────────────┼─────────
  NoHorizontal    │ -15%      │ -8%        │ -11%
  NoVertical      │ -23%      │ -12%       │ -18%
  NoFeature       │ -41%      │ -31%       │ -35%
  ────────────────┼───────────┼────────────┼─────────
  Full OpenSage   │ SOTA 🥇   │ SOTA 🥇    │ +best

Key findings:
  - Both topologies contribute independently
  - Vertical topology has larger impact (task decomposition crucial)
  - Horizontal ensemble especially useful for CyberGym (ambiguous tasks)
  - Full feature set (memory + tooling + topology) = best performance
""")


def run_live_topology_demo():
    """Run live topology demo with real API calls."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("\n⚠  ANTHROPIC_API_KEY not set.")
        return

    from opensage import OpenSage

    engine = OpenSage(api_key=api_key, verbose=True)

    # Write a simple coding challenge
    challenge_code = """
def merge_sorted_lists(list1, list2):
    '''Merge two sorted lists into one sorted list.
    Current implementation has a bug.'''
    result = []
    i, j = 0, 0
    while i < len(list1) and j < len(list2):
        if list1[i] < list2[j]:
            result.append(list1[i])
            i += 1
        else:
            result.append(list2[j])
            j += 1
    # Bug: missing remainder handling
    return result
"""
    engine.executor.write_file("merge_challenge.py", challenge_code)

    # Demo 1: Vertical topology
    print("\n" + "="*60)
    print("DEMO: Vertical Topology on coding challenge")
    print("="*60)

    start = time.time()
    result = engine.solve(
        f"Fix the merge_sorted_lists function in {engine.executor.work_dir}/merge_challenge.py "
        f"and verify with test cases for: [], [1], [1,3], [1,3,5] merged with [2,4,6]",
        topology="vertical",
    )
    elapsed = time.time() - start

    print(f"\nVertical result ({elapsed:.1f}s):")
    print(result[:500])

    engine.executor.cleanup()


if __name__ == "__main__":
    demo_topology_concepts()

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if api_key:
        run_live_topology_demo()
    else:
        print("\n[Set ANTHROPIC_API_KEY to run live topology demos]")
